safe: true
strict_front_matter: true
timezone: "Europe/Amsterdam"

title: "NNAOC"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass/
  style: compressed


# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
